syntax = "proto3";

package ru.taska.admin_invite_user.v1;

import "v1/common.proto";

option java_multiple_files = true;
option java_package = "ru.taska.api.auth.admin.inviteuser.v1";
option java_outer_classname = "AdminInviteUserApiProto";

service AdminInviteUserService {
  rpc InviteUser(InviteUserRequest) returns (InviteUserResponse);
}

/**
 * Запрос на приглашение пользователя.
 */
message InviteUserRequest {
  /**
   * Заголовок запроса.
   */
  ru.taska.common.v1.Header header = 1;

  /**
   * Тело запроса.
   */
  InviteUserRequestBody body = 2;
}

/**
 * Тело запроса на приглашение пользователя.
 */
message InviteUserRequestBody {
  /**
   * Email пользователя.
   */
  string email = 1;

  /**
   * Отображаемое имя пользователя.
   */
  string display_name = 2;
}

/**
 * Ответ на приглашение пользователя.
 */
message InviteUserResponse {
  /**
   * Идентификатор пользователя.
   */
  string user_id = 1;

  /**
   * Статус пользователя (INVITED/ACTIVE/BLOCKED).
   */
  ru.taska.common.v1.UserStatus status = 2;
}
