server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5437/notification_db}
    username: ${SPRING_R2DBC_USERNAME:taska}
    password: ${SPRING_R2DBC_PASSWORD:taska}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5437/notification_db}
    user: ${SPRING_LIQUIBASE_USERNAME:taska}
    password: ${SPRING_LIQUIBASE_PASSWORD:taska}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  email:
    retry-delay-seconds: 60

logging:
  level:
    org.liquibase: INFO
    liquibase: INFO