server:
  port: ${SERVER_PORT:8085}

spring:
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9095}
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5437/notification_db}
    username: ${SPRING_R2DBC_USERNAME:taska}
    password: ${SPRING_R2DBC_PASSWORD:taska}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5437/notification_db}
    user: ${SPRING_LIQUIBASE_USERNAME:taska}
    password: ${SPRING_LIQUIBASE_PASSWORD:taska}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:notification-service}
      auto-offset-reset: earliest
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

notification:
  email:
    retry-delay: ${NOTIFICATION_EMAIL_RETRY_DELAY:1m}

logging:
  level:
    ru.taska: ${LOG_LEVEL_ROOT:INFO}
    liquibase: ${LOG_LEVEL_LIQUIBASE:INFO}
    org.apache.kafka: ${LOG_LEVEL_KAFKA:WARN}