server:
  port: ${NOTIFICATION_SERVER_PORT:8085}

spring:
  application:
    name: notification-service
  grpc:
    server:
      port: ${NOTIFICATION_GRPC_SERVER_PORT:9095}
  r2dbc:
    url: ${NOTIFICATION_SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5437/notification_db}
    username: ${NOTIFICATION_SPRING_R2DBC_USERNAME:taska}
    password: ${NOTIFICATION_SPRING_R2DBC_PASSWORD:taska}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${NOTIFICATION_SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5437/notification_db}
    user: ${NOTIFICATION_SPRING_LIQUIBASE_USERNAME:taska}
    password: ${NOTIFICATION_SPRING_LIQUIBASE_PASSWORD:taska}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${NOTIFICATION_KAFKA_CONSUMER_GROUP_ID:notification-service}
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mail:
    host: ${NOTIFICATION_MAIL_HOST:smtp.gmail.com}
    port: ${NOTIFICATION_MAIL_PORT:587}
    username: ${NOTIFICATION_MAIL_USERNAME:taskainator@gmail.com}
    password: ${NOTIFICATION_MAIL_PASSWORD:wjbq xepa zknf szbp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
    # Разрешает сбор метрик Prometheus
  metrics:
    tags:
      #Prometheus сразу поймет, от какого сервиса пришли метрики
      application: ${spring.application.name}

kafka:
  consumer:
    retry:
      max-attempts: ${KAFKA_CONSUMER_RETRY_MAX_ATTEMPTS:3}
      interval: ${KAFKA_CONSUMER_RETRY_INTERVAL:3s}
  consumer-group: ${NOTIFICATION_KAFKA_CONSUMER_GROUP_ID:notification-service}
  topics:
    project-events: ${NOTIFICATION_KAFKA_TOPICS_PROJECT_EVENTS:project.events}
    user-events: ${NOTIFICATION_KAFKA_TOPICS_USER_EVENTS:user.events}
    issue-events: ${NOTIFICATION_KAFKA_TOPICS_ISSUE_EVENTS:issue.events}

notification:
  email:
    retry-delay: ${NOTIFICATION_EMAIL_RETRY_DELAY:1m}

logging:
  level:
    ru.taska: ${NOTIFICATION_LOG_LEVEL_ROOT:INFO}
    liquibase: ${NOTIFICATION_LOG_LEVEL_LIQUIBASE:INFO}
    org.apache.kafka: ${NOTIFICATION_LOG_LEVEL_KAFKA:WARN}