syntax = "proto3";

package ru.taska.proto;

option java_multiple_files = true;
option java_package = "ru.taska.proto";
option java_outer_classname = "AuthProto";

service AuthService {
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc Refresh (RefreshRequest) returns (RefreshResponse);
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
    int64 expires_in = 3; // seconds
}

message RefreshRequest {
    string refresh_token = 1;
}

message RefreshResponse {
    string access_token = 1;
    string refresh_token = 2; // может быть новым при ротации
    int64 expires_in = 3;
}