syntax = "proto3";

package ru.taska.project.v1;

import "v1/common.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option java_multiple_files = true;
option java_package = "ru.taska.api.project.v1";
option java_outer_classname = "ProjectApiProto";

enum ProjectRole {
  PROJECT_ROLE_UNSPECIFIED = 0;
  PROJECT_ROLE_ADMIN = 1;
  PROJECT_ROLE_MEMBER = 2;
  PROJECT_ROLE_VIEWER = 3;
}

service ProjectService {
  /**
   * Создаёт новый проект.
   */
  rpc CreateProject (CreateProjectRequest) returns (ProjectResponse);

  /**
   * Возвращает проект по идентификатору.
   */
  rpc GetProject (GetProjectRequest) returns (ProjectResponse);

  /**
   * Возвращает список всех проектов по идентификатору пользователя.
   */
  rpc ListMyProjects (ListMyProjectsRequest) returns (ListMyProjectsResponse);

  /**
   * Добавляет участника в проект.
   */
  rpc AddProjectMember (AddProjectMemberRequest) returns (AddProjectMemberResponse);

  /**
   * Удаляет участника из проекта.
   */
  rpc RmProjectMember (RmProjectMemberRequest) returns (RmProjectMemberResponse);

  /**
   * Меняет роль участника проекта.
   */
  rpc ChangeProjectMemberRole (ChangeProjectMemberRoleRequest) returns (ChangeProjectMemberRoleResponse);

  /**
   * Проверяет роль пользователя в проекте.
   */
  rpc CheckProjectMemberRole(CheckProjectMemberRoleRequest) returns (CheckProjectMemberRoleResponse);
}

message CreateProjectRequest {
  ru.taska.common.v1.Header header = 1;
  CreateProjectRequestBody body = 2;
}

message CreateProjectRequestBody {
  string project_key = 1;
  string name = 2;
  string user_id = 3;
}

message GetProjectRequest {
  ru.taska.common.v1.Header header = 1;
  GetProjectRequestBody body = 2;
}

message GetProjectRequestBody {
  string project_id = 1;
  string actor_user_id=2;
}

message ListMyProjectsRequest {
  ru.taska.common.v1.Header header = 1;
  ListMyProjectsRequestBody body = 2;
}

message ListMyProjectsRequestBody {
  string user_id = 1;
}

/**
 * Запрос на проверку роли пользователя в проекте.
 */
message CheckProjectMemberRoleRequest {
  /**
   * Заголовок запроса.
   */
  ru.taska.common.v1.Header header = 1;

  /**
   * Тело запроса.
   */
  CheckProjectMemberRoleRequestBody body = 2;
}

/**
 * Тело запроса на проверку роли пользователя в проекте.
 */
message CheckProjectMemberRoleRequestBody {
  /**
   * Идентификатор проекта.
   */
  string project_id = 1;

  /**
   * Идентификатор участника проекта.
   */
  string user_id = 2;
}

message ProjectResponse {
  string id = 1;
  string project_key = 2;
  string name = 3;
  string created_by = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
  optional google.protobuf.Timestamp archived_at = 7;
}

message ListMyProjectsResponse {
  repeated ProjectResponse project_response = 1;
}

message AddProjectMemberRequest {
  ru.taska.common.v1.Header header = 1;
  AddProjectMemberRequestBody body = 2;
}

message AddProjectMemberRequestBody {
  string added_member_id = 1;
  string actor_user_id = 2;
  ProjectRole role = 3;
  string project_id = 4;
}

message AddProjectMemberResponse {
  string added_member_id = 1;
  string project_id = 2;
  ProjectRole role = 3;
}

message RmProjectMemberRequest {
  ru.taska.common.v1.Header header = 1;
  RmProjectMemberRequestBody body = 2;
}

message RmProjectMemberRequestBody {
  string deleted_member_id = 1;
  string actor_user_id = 2;
  string project_id = 3;
}

message RmProjectMemberResponse {
  string deleted_member_id = 1;
  string project_id = 2;
}

message ChangeProjectMemberRoleRequest {
  ru.taska.common.v1.Header header = 1;
  ChangeProjectMemberRoleRequestBody body = 2;
}

message ChangeProjectMemberRoleRequestBody {
  string changed_member_id = 1;
  string actor_user_id = 2;
  ProjectRole role = 3;
  string project_id = 4;
}

message ChangeProjectMemberRoleResponse {
  string changed_member_id = 1;
  ProjectRole role = 2;
  string project_id = 3;
}

/**
 * Ответ проверки роли пользователя в проекте.
 */
message CheckProjectMemberRoleResponse {
  /**
   * Роль пользователя.
   */
  ProjectRole role = 1;

  /**
   * Является ли пользователь участником проекта.
   */
  bool is_member = 2;

  /**
   * Существует ли проект.
   */
  bool project_exists = 3;
}
