spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5435/workflow_db}
    username: ${SPRING_R2DBC_USERNAME:taska}
    password: ${SPRING_R2DBC_PASSWORD:taska}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    ru.taska: ${LOG_LEVEL_ROOT:INFO}
    liquibase: ${LOG_LEVEL_LIQUIBASE:INFO}