server:
  port: ${WORKFLOW_SERVER_PORT:8083}

spring:
  grpc:
    server:
      port: ${WORKFLOW_GRPC_SERVER_PORT:9093}
  r2dbc:
    url: ${WORKFLOW_SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5435/workflow_db}
    username: ${WORKFLOW_SPRING_R2DBC_USERNAME:taska}
    password: ${WORKFLOW_SPRING_R2DBC_PASSWORD:taska}
  liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-master.yaml
      url: ${WORKFLOW_SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5435/workflow_db}
      user: ${WORKFLOW_SPRING_LIQUIBASE_USERNAME:taska}
      password: ${WORKFLOW_SPRING_LIQUIBASE_PASSWORD:taska}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    ru.taska: ${WORKFLOW_LOG_LEVEL_ROOT:INFO}
    liquibase: ${WORKFLOW_LOG_LEVEL_LIQUIBASE:INFO}