spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5434/project_db}
    username: ${SPRING_R2DBC_USERNAME:taska}
    password: ${SPRING_R2DBC_PASSWORD:taska}

  liquibase:
    enabled: true
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5434/project_db}
    user: ${SPRING_R2DBC_USERNAME:taska}
    password: ${SPRING_R2DBC_PASSWORD:taska}
    change-log: classpath:/db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true