package ru.taska.dto;

public enum Violation {
    WORKFLOW_NOT_FOUND,
    TRANSITION_NOT_FOUND,
    TRANSITION_DOESNT_BELONG_TO_WORKFLOW,
    FROM_STATUS_DOESNT_MATCH,
    CURRENT_STATUS_NOT_FOUND,
    TARGET_STATUS_NOT_FOUND,
    FAILED_PRECONDITION
}
