package ru.taska.dto;

public enum WorkflowCreationViolationType {
    BLANK_NAME,
    TOO_LONG_NAME,
    ISSUE_TYPE_LIST_EMPTY,
    BLANK_STATUS_KEY,
    INVALID_STATUS_KEY_FORMAT,
    DUPLICATE_ISSUE_TYPE,
    DUPLICATE_STATUS_KEY,
    DUPLICATE_STATUS_SORT_ORDER,
    INVALID_STATUS_CATEGORY,
    TRANSITION_REFERENCES_UNKNOWN_STATUS,
    SELF_TRANSITION,
    DUPLICATE_TRANSITION,
    DUPLICATE_TRANSITION_SORT_ORDER,
    NEGATIVE_SORT_ORDER
}
