package ru.taska.domain;

public enum NotificationType {
    ISSUE_ASSIGNED,
    ISSUE_TRANSITIONED,
    ISSUE_CREATED,
    ISSUE_UPDATED,
    ISSUE_DELETED,
    USER_INVITED,
    USER_ACTIVATED,
    PROJECT_CREATED,
    MEMBER_ADDED,
    MEMBER_UPDATED,
    MEMBER_REMOVED
}
